### PR TITLE
Propose initial meeting

### PR DESCRIPTION
**Pull request by chrisdickinson**
/cc @endocrimes, @Walther, @brooksmtownsend, @squillace

Hi folks! I'd like to meet up in advance of the Feb 8th WASI meeting, at which there will be a vote on moving this proposal to phase 1. It looks like 16:00 UTC might be the best overlap for everyone (that's 8am Portland time, 6pm UTC+2).

I propose we meet up at that time sometime in the next two weeks. I've left the date open for now – any date between Jan 22nd through Feb 2nd is okay!

So! I have two requests:

1. Please let me know which dates work for you! You can either comment here or, if you'd prefer to reach out privately, email me at chris at dylibso dot com.
2. Let me know on this issue if using the email address associated with your GitHub profile is okay, or if you want me to use another email. If you want to keep that email private, please email me (chris at dylibso dot com) from your preferred address.

And if you have suggestions on better ways to do this sort of scheduling, please let me know :smile:

I plan to merge this on Friday with a definite date set, then email invites to the addresses listed on everyone's GitHub profiles. (If another email works better, please comment here that you'll reach out & email me from your preferred address!)

(Apologies for the delay on getting this out, we've had some :sparkles: _interesting weather_ :sparkles: these last few days. I hope everyone affected is staying safe & warm!)

### CODE REVIEW

**Comment by brooksmtownsend** [comment]
The email on my GitHub profile works great! I think I have a personal and professional one on there, either works fine.

I used https://www.timeanddate.com/worldclock/meetingdetails.html?year=2024&month=1&day=17&hour=16&min=0&sec=0&p1=202&p2=263&p3=1440 to put together a few time zones, I neglected to add all of them but it's a solid way to add your own!

Every day from Jan 22 to Feb 2 works for me other than Monday Jan 29. I would suggest we keep away from Tuesday Jan 23 and Jan 30 as both of those time slots are occupied by the Wasm WG and then the Bytecode Alliance community stream. So, on my end / community considered, I think **Jan 22, 24, 25, 26, 31 / Feb 1, 2** would work!

**Comment by squillace** [comment]
yo. you betcha. I'm CET based, so morning PDT is preferable, though I defer to the wisdom of crowds. I'm totes interested, so pick a day and I'll see about making it work. I think there's a plumbers conf in late Jan, like the 28th? but I can't recall and need to go to bed. :-)

**Comment by Walther** [comment]
Hiya again! Any evening Jan 22 through Feb 2 works for me, **except for the  Thursdays** (25th, 1st). I also have a tentative event on 23rd that might or might not happen - but it seems that it was already mentioned above as a day to avoid anyway. Looking forward to the first meeting!

**Comment by endocrimes** [comment]
👋 I'm free 22nd-25th, then again 30th - 1st and like @squillace would definitely prefer mornings PDT (being in CET).  Either the email in my github profile or danielle@fermyon.com works :)

**Comment by chrisdickinson** [comment]
OK! Invites should be sent[^1] (via Zoom) for Jan 31st at 16:00-17:00 UTC. (I've reserved the full hour but it's likely that we'll run shorter.) Thanks, all!

[^1]: Assuming I've done this correctly! 😅 Please do reach out to me at chris@dylibso.com (or via discord `@chrisdickinson`) if you haven't received an invite!

**Pull request merged**
